/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "prefs.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

int
main (int argc, char *argv[])
{
	GtkWidget *window;
	GtkWidget *window_about;
	gtkTermPref* pref;
	int c;
	static struct option long_options[] =
	{
		{"help", 0, 0, 'h'},
		{"version", 0, 0, 'v'},
		{"loginshell", 0, 0, 'l'},
		{"blink", 0, 0, 'b'},
		{"beep", 0, 0, 'a'},
		{0, 0, 0, 0}
	};


#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);
	
	pref = gtkTermPref_get();

	add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
	add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

	while((c=getopt_long(argc, argv, "hvl", long_options, NULL)) != EOF)
	{
		switch (c)
		{
			case 'a':
				pref->beep = TRUE;
			break;
			case 'b':
				pref->blink = TRUE;
			break;
			case 'l':
				pref->login_shell = TRUE;
			break;
			case 'v':
				printf("gtkterm2 version: %s\n", VERSION);
				exit(0);
			break;
			case 'h':
				printf("\ngtkterm2 [-abhvl]\n\n\ta --beep:\tbeep\n\tb --blink:\tblink in shell\n\th --help:\tthis help text\n\tv --version:\tversion informations\n\tl --loginshell:\tstart gtkterm2 with a login shell\n\n");
				exit(0);
			break;
		}
	}

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window = create_window (pref);
  window_about = create_window_about();

  GLADE_HOOKUP_OBJECT (window, window_about, "window_about");

  gtk_widget_show (window);

  gtk_main ();
  return 0;
}
